config/routes.rb
Langquest::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root              to: 'static_pages#home'
  match '/trivial', to: 'static_pages#trivial'

  namespace :api do
    namespace :core, defaults: { format: 'json' } do
      get 'vocabulary'
    end
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  attr_accessible :name, :word_ids
  has_and_belongs_to_many :words
end

app/models/word.rb
# == Schema Information
#
# Table name: words
#
#  id         :integer          not null, primary key
#  english    :string(255)
#  spanish    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Word < ActiveRecord::Base
  attr_accessible :english, :spanish, :category_ids
  has_and_belongs_to_many :categories
end

app/controllers/api/core_controller.rb
class Api::CoreController < ApplicationController
  before_filter :get_languages
  respond_to :json

  def vocabulary
    logger.info { @lang_from }
    logger.info { @lang_to }
    @word = Word.order("RANDOM()").first
    @wrongs = Word.where("english <> ?", @word.english).order("RANDOM()").first(3)
    respond_with({
      word: @word[@lang_from],
      right: @word[@lang_to],
      wrongs: @wrongs.collect{|w| w[@lang_to]}
    })
  end

  private

  def get_languages
    @current_langs = ['english','spanish']
    @lang_from = @current_langs[0]
    @lang_to = @current_langs[1]

    @lang_from = params[:from] if @current_langs.include? params[:from]
    @lang_to = params[:to] if @current_langs.include? params[:to]

    # reverting languages
    @lang_from,@lang_to = @lang_to,@lang_from if params[:revert]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def trivial
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html{ :"ng-app" => "trivialModule" }
  %head
    %title Langquest
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = yield :extra_js
    = csrf_meta_tags
  %body
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/static_pages/home.html.haml
%h1 StaticPages#home
= link_to "trivial", trivial_path

app/views/static_pages/trivial.html.haml
- content_for :extra_js do
  = javascript_include_tag "angular"

.trivial{ :"ng-controller" => "TrivialController" }
  %h1 Chusco Trivial
  #data
    .score
      Score: {{ player.score || 0 }} {{ player.badges.length || 0 }}
    .badges
      {{ player.badges.length || 0 }} badges earned
      %ul
        %li{ :"ng-repeat" => "badge in player.badges"}
          {{ badge.name }}

    .board{ :style => "width: {{board.size}}px; height: {{board.size}}px; border-radius: {{board.size}}px;" }
      .tile{ :"ng-repeat" => "tile in board.tiles", :style => "{{ $index | tile_style: {bg_color: tiles[tile.type].color, board_size: board.size, num_tiles: board.tiles.length, tile_sizes: tile_size, tile_badge: tile.badge} }}", :"ng-class" => "{big: tile.badge}" }

app/views/words/random.html.erb
<h1>Words#random</h1>
<p>Find me in app/views/words/random.html.erb</p>